const f1 = ["alice","anaïs","andrée","anne","annick","annie","audrey","aurélie","bernadette","brigitte","béatrice","camille","caroline","catherine","chantal","charlotte","chloé","christelle","christiane","christine","claire","claudine","colette","corinne","cécile","céline","danielle","delphine","denise","dominique","éliane","elisabeth","élise","élodie","émilie","emma","évelyne","florence","françoise","geneviève","georgette","germaine","ginette","gisèle","henriette","hélène","isabelle","jacqueline","jeanne","jeannine","josette","josiane","julie","juliette","karine","lætitia","laura","laurence","louise","lucie","lucienne","léa","madeleine","manon","marcelle","marguerite","maria","marie","marine","marion","marthe","martine","mathilde","michelle","michèle","mireille","monique","mélanie","nadine","nathalie","nicole","odette","patricia","paulette","pauline","raymonde","renée","sandrine","sarah","simone","sophie","stéphanie","suzanne","sylvie","thérèse","valérie","virginie","véronique","yvette","yvonne"];

const f2 = ["abida","adiba","afaf","afifa","ahlem","aïcha","aïda","alia","amana","amel","amina","amira","anissa","asma","assia","atika","aya","aziza","badra","basma","chadia","chafia","chafika","chahra","chahrazad","chakira","dalila","djamila","douha","dounia","emna","fadil","faiza","farida","faten","fatiha","fatima","fouzia","ghalia","ghania","habiba","hadia","hafida","hafsa","hakima","hala","halima","hamida","hanane","hania","hanna","hayet","hawa","ibtissem","ikram","ilhem","imane","ines","karima","kawtar","kenza","khadidja","khalida","latifa","leila","mabrouka","maha","mahbouba","maissa","majda","malika","manel","meriem","moufida","mouna","mounira","nabila","nacira","nadia","nadjiba","nafissa","naïma","najet","nawel","naziha","nedjma","nour","rachida","rahma","raja","rawda","safia","saïda","sakina","saliha","salima","saloua","samia","samira","sana","selma","sihème","soraya","souad","wafa","wahiba","warda","wasill","wide","yamina","yasmine","yousra","zineb","zohra"];

const f3 = ["adèle","adeline","adrienne","agathe","agnès","aimée","albertine","alexandra","alexia","alice","alicia","aline","alix","alphonsine","amandine","ambre","amélie","anaïs","andréa","andrée","angèle","angelique","anna","anne","anne-marie","anne-sophie","annette","annick","annie","antoinette","arlette","assia","aude","audrey","augusta","augustine","aurélie","aurore","axelle","aya","béatrice","benedicte","bernadette","berthe","blanche","brigitte","camille","candice","capucine","carine","carla","carole","caroline","cassandra","catherine","cathy","cécile","célia","céline","chantal","charlène","chloé","christel","christelle","christiane","christine","cindy","claire","clara","claude","claudette","claudine","clémence","clémentine","clotilde","colette","coline","coralie","corinne","cynthia","daniele","danielle","deborah","delphine","denise","dominique","édith","elena","éliane","élisa","elisabeth","élise","élodie","éloïse","elsa","émeline","émilie","émilienne","emma","emmanuelle","ernestine","estelle","eugénie","eva","evelyne","fabienne","fanny","faustine","fernande","florence","francine","françoise","frédérique","gabrielle","gaëlle","geneviève","georgette","geraldine","germaine","ghislaine","gilberte","ginette","gisèle","hélène","héloïse","henriette","huguette","inaya","inès","irène","irma","isabelle","jacqueline","jade","janine","jeanine","jeanne","jeannine","jennifer","jessica","jocelyne","joëlle","johanna","josephine","josette","josiane","julia","julie","julienne","juliette","justine","karine","katia","kelly","kenza","lætitia","lana","laura","laure","laurence","laurie","laurine","léa","léana","léane","léna","léone","léonie","léontine","liliane","lilou","lily","lina","lisa","lise","lola","lou","louane","louise","louna","lucette","lucie","lucienne","lucile","ludivine","luna","lydie","madeleine","maelle","maelys","maëlys","maeva","magali","manon","marcelle","margaux","margot","marguerite","maria","marie","marie-christine","marie-claire","marie-claude","marie-france","marie-françoise","marie-hélène","marie-josé","marie-laure","marie-louise","marie-pierre","marie-thérèse","marina","marine","marion","marjorie","marthe","martine","maryline","maryse","maryvonne","maud","mauricette","mélanie","mélina","mélissa","mia","michèle","micheline","michelle","mila","mireille","monique","morgane","muriel","murielle","myriam","nadège","nadia","nadine","nathalie","nelly","nicole","nina","noémie","océane","odette","odile","olga","olivia","ophélie","pascale","patricia","paule","paulette","pauline","philomène","pierrette","rachel","raymonde","régine","reine","renée","rolande","romane","rosa","rosalie","rose","sabine","sabrina","salomé","sandra","sandrine","sara","sarah","séverine","simone","sofia","solange","solène","sonia","sophie","stéphanie","suzanne","sylviane","sylvie","thérèse","valentine","valérie","vanessa","véronique","victoire","victoria","victorine","virginie","viviane","yasmine","yolande","yvette","yvonne","zoé"];

const f4 = ['esther', 'clothilde', 'radegonde', 'théodechilde', 'marcowefa', 'audovère', 'galswinthe', 'frédégonde', 'basine', 'ultrogothe', 'ingonde', 'chunsine', 'gondioque', 'arégonde', 'vuldetrade', 'ingeberge', 'méroflède', 'haldetrude', 'bertrude', 'sichilde', 'gomatrude', 'nantilde', 'wulfégonde', 'berchilde', 'chimnechilde', 'bathilde', 'bilichilde', 'bertrade', 'himiltrude', 'désirée', 'hildegarde', 'fastrade', 'luitgarde', 'ermengarde', 'judith', 'richilde', 'adélaïde', 'richarde', 'théodérade', 'frédérune', 'edwige', 'gerberge', 'rozala', 'berthe', 'aliénor', 'ingeburge', 'isabeau', 'claude', 'marie-antoinette', 'joséphine', 'marie-amélie' ];

const h1 = ["adrien","alain","albert","alexandre","alexis","andré","anthony","antoine","arnaud","arthur","benjamin","benoît","bernard","bruno","cédric","charles","christian","christophe","claude","clément","damien","daniel","david","denis","didier","dominique","émile","emmanuel","enzo","éric","fabien","fabrice","fernand","florian","francis","franck","françois","frédéric","gabriel","georges","gilbert","gilles","guillaume","guy","gérard","henri","hervé","hugo","jacques","jean","jean-claude","jean-luc","jean-pierre","jérémy","jérôme","joseph","joël","jules","julien","kevin","laurent","louis","lucas","lucien","ludovic","léon","marc","marcel","mathieu","maurice","maxime","michel","mickael","nicolas","olivier","pascal","patrice","patrick","paul","philippe","pierre","quentin","raphaël","raymond","rené","robert","roger","roland","romain","serge","stéphane","sylvain","sébastien","thierry","thomas","théodore","victor","vincent","xavier","yves"];

const h2 = ["adama","adel","adib","adil","ahmed","aissa","ali","amine","amirou","anas","anis","anouar","ayoub","azziz","bachir","badr","baligh","bilal","bouzid","chafik","chahid","chaker","chams","chawki","chokri","daoud","djamel","djillali","fadel","fahim","fares","farid","fathi","faudel","faouzi","fayçal","ferhat","fouad","djibril","ghani","habib","hafid","hakim","halim","hamid","hani","hichem","hilal","hosni","ismail","imed","jabar","kader","kamel","karim","khaled","khalilou","larbi","lotfi","mabrouk","mahboub","mahfoud","mahmoud","malik","marwan","mehdi","mohamed","moktar","moncef","mourad","nabil","nacer","nadir","nadjib","nassim","nazim","nouh","oumarou","othmane","oussama","rabah","rachid","rafik","rahal","ramzi","raouf","rayan","réda","redouane","riad","rochdi","sabri","sala","sali","sam","sedi","sofiane","tahar","taimim","tarek","tayeb","tawfik","wallid","wassim","yacoub","yezid","youce","youne","zahid","zaïm","zakaria","zaki","ziad","zoheir"];

const h3 = ["aaron","abel","achille","adam","adolphe","adrien","aime","alain","albert","alexandre","alexis","alfred","alphonse","amine","andré","ange","anthony","antoine","antonin","armand","arnaud","arsène","arthur","auguste","augustin","aurélien","axel","baptiste","bastien","benjamin","benoît","bernard","bertrand","brice","bruno","camille","cédric","celestin","charles","christian","christophe","christopher","claude","claudius","clément","constant","corentin","cyril","cyrille","damien","daniel","david","denis","désiré","didier","dimitri","dominique","dorian","dylan","edmond","edouard","élie","eliott","émile","émilien","emmanuel","enzo","éric","ernest","erwan","esteban","ethan","étienne","eugène","evan","fabien","fabrice","félix","ferdinand","fernand","florent","florian","francis","franck","françois","frédéric","gabin","gabriel","gaëtan","gaspard","gaston","geoffrey","georges","gérald","gérard","germain","gilbert","gilles","gregory","guillaume","gustave","guy","henri","hervé","hubert","hugo","ilyes","jackie","jacky","jacques","jean","jean-baptiste","jean-christophe","jean-claude","jean-françois","jean-jacques","jean-louis","jean-luc","jean-marc","jean-marie","jean-michel","jean-paul","jean-philippe","jean-pierre","jean-yves","jeremie","jeremy","jerome","jimmy","joël","johan","jonathan","jordan","josé","joseph","jules","julien","justin","karim","kevin","killian","kléber","kylian","laurent","lenny","léo","léon","leopold","liam","lilian","lionel","loïc","lorenzo","louis","luc","lucas","lucien","ludovic","mael","maël","malo","manuel","marc","marceau","marcel","marie","marius","martial","martin","matéo","mathéo","mathias","mathieu","mathis","mathys","mattéo","matthieu","maurice","max","maxence","maxime","mehdi","michael","michel","mickael","mohamed","morgan","nathan","nicolas","noa","noah","noe","noé","noël","nolan","norbert","octave","olivier","pascal","patrice","patrick","paul","philippe","pierre","quentin","raoul","raphaël","rayan","raymond","regis","rémi","rémy","rené","richard","robert","robin","roger","roland","romain","ryan","sacha","samuel","sébastien","serge","simon","stéphane","steven","sylvain","théo","théodore","théophile","thibault","thibaut","thierry","thomas","tiago","timeo","timéo","titouan","tom","tony","tristan","valentin","victor","vincent","william","xavier","yanis","yann","yannick","yoann","yves","yvon"];

const h4 = ['clovis', 'clodomir', 'thibert', 'childebert', 'clotaire', 'caribert', 'sigebert', 'chilpéric', 'gontran', 'dagobert', 'pépin', 'carloman', 'eudes', 'lothaire', 'hugues'];

const ninas = ["Isabella","Olivia","Alexis","Sofía","Victoria","Amelia","Alexa","Julia","Camila","Alexandra","Maya","Andrea","Ariana","María","Eva","Angelina","Valeria","Natalia","Isabel","Sara","Liliana","Adriana","Juliana","Gabriela","Daniela","Valentina","Lila","Vivian","Nora","Ángela","Elena","Clara","Eliana","Alana","Miranda","Amanda","Diana","Ana","Penélope","Aurora","Alexandría","Lola","Alicia","Amaya","Alexia","Jazmín","Mariana","Alina","Lucía","Fátima","Ximena","Laura","Cecilia","Alejandra","Esmeralda","Verónica","Daniella","Miriam","Carmen","Iris","Guadalupe","Selena","Fernanda","Angélica","Emilia","Lía","Tatiana","Mónica","Carolina","Jimena","Dulce","Talía","Estrella","Brenda","Lilian","Paola","Serena","Celeste","Viviana","Elisa","Melina","Gloria","Claudia","Sandra","Marisol","Asia","Ada","Rosa","Isabela","Regina","Elsa","Perla","Raquel","Virginia","Patricia","Linda","Marina","Leila","América","Mercedes"];


const ninos = ["Daniel","David","Gabriel","Benjamín","Samuel","Lucas","Ángel","José","Adrián","Sebastián","Xavier","Juan","Luis","Diego","Óliver","Carlos","Jesús","Alex","Max","Alejandro","Antonio","Miguel","Víctor","Joel","Santiago","Elías","Iván","Óscar","Leonardo","Eduardo","Alan","Nicolás","Jorge","Omar","Paúl","Andrés","Julián","Josué","Román","Fernando","Javier","Abraham","Ricardo","Francisco","César","Mario","Manuel","Édgar","Alexis","Israel","Mateo","Héctor","Sergio","Emiliano","Simón","Rafael","Martín","Marco","Roberto","Pedro","Emanuel","Abel","Rubén","Fabián","Emilio","Joaquín","Marcos","Lorenzo","Armando","Adán","Raúl","Julio","Enrique","Gerardo","Pablo","Jaime","Saúl","Esteban","Gustavo","Rodrigo","Arturo","Mauricio","Orlando","Hugo","Salvador","Alfredo","Maximiliano","Ramón","Ernesto","Tobías","Abram","Noé","Guillermo","Ezequiel","Lucián","Alonzo","Felipe","Matías","Tomás","Jairo"];

const feminins = [...f1, ...f2, ...f3, ...ninas, ...f4];

const masculins = [...h1, ...h2, ...h3, ...ninos, ...h4];

export {feminins, masculins};
