const liste = [
    ["06030", {nom:"Le Cannet", a:"au Cannet"}],
    ["06149", {nom:"La Trinité", a:"à la Trinité"}],
    ["07319", {nom:"Le Teil", a:"au Teil"}],
    ["10081", {nom:"La Chapelle-Saint-Luc", a:"à la Chapelle-Saint-Luc"}],
    ["13028", {nom:"La Ciotat", a:"à la Ciotat"}],
    ["13037", {nom:"La Fare-les-Oliviers", a:"à la Fare-les-Oliviers"}],
    ["13071", {nom:"Les Pennes-Mirabeau", a:"aux Pennes-Mirabeau"}],
    ["17300", {nom:"La Rochelle", a:"à la Rochelle"}],
    ["27016", {nom:"Les Andelys", a:"aux Andelys"}],
    ["29235", {nom:"Le Relecq-Kerhuon", a:"au Relecq-Kerhuon"}],
    ["30011", {nom:"Les Angles", a:"aux Angles"}],
    ["30133", {nom:"Le Grau-du-Roi", a:"au Grau-du-Roi"}],
    ["31526", {nom:"La Salvetat-Saint-Gilles", a:"à la Salvetat-Saint-Gilles"}],
    ["31561", {nom:"L’Union", a:"à l’Union"}],
    ["32160", {nom:"L’Isle-Jourdain", a:"à l’Isle-Jourdain"}],
    ["33069", {nom:"Le Bouscat", a:"au Bouscat"}],
    ["33200", {nom:"Le Haillan", a:"au Haillan"}],
    ["33519", {nom:"Le Taillan-Médoc", a:"au Taillan-Médoc"}],
    ["33527", {nom:"Le Teich", a:"au Teich"}],
    ["33529", {nom:"La Teste-de-Buch", a:"à la Teste-de-Buch"}],
    ["34090", {nom:"Le Crès", a:"au Crès"}],
    ["34344", {nom:"La Grande-Motte", a:"à la Grande-Motte"}],
    ["35240", {nom:"Le Rheu", a:"au Rheu"}],
    ["37195", {nom:"La Riche", a:"à la Riche"}],
    ["38193", {nom:"L’Isle-d’Abeau", a:"à l’Isle-d’Abeau"}],
    ["38317", {nom:"Le Pont-de-Claix", a:"au Pont-de-Claix"}],
    ["38509", {nom:"La Tour-du-Pin", a:"à la Tour-du-Pin"}],
    ["42044", {nom:"Le Chambon-Feugerolles", a:"au Chambon-Feugerolles"}],
    ["43157", {nom:"Le Puy-en-Velay", a:"au Puy-en-Velay"}],
    ["44035", {nom:"La Chapelle-sur-Erdre", a:"à la Chapelle-sur-Erdre"}],
    ["44055", {nom:"La Baule-Escoublac", a:"à la Baule-Escoublac"}],
    ["44084", {nom:"Le Loroux-Bottereau", a:"au Loroux-Bottereau"}],
    ["44198", {nom:"Les Sorinières", a:"aux Sorinières"}],
    ["45075", {nom:"La Chapelle-Saint-Mesmin", a:"à la Chapelle-Saint-Mesmin"}],
    ["45191", {nom:"Le Malesherbois", a:"au Malesherbois"}],
    ["47201", {nom:"Le Passage", a:"au Passage"}],
    ["49080", {nom:"Les Hauts-d’Anjou", a:"aux Hauts-d’Anjou"}],
    ["49246", {nom:"Les Ponts-de-Cé", a:"aux Ponts-de-Cé"}],
    ["50041", {nom:"La Hague", a:"à la Hague"}],
    ["59143", {nom:"La Chapelle-d’Armentières", a:"à la Chapelle-d’Armentières"}],
    ["59368", {nom:"La Madeleine", a:"à la Madeleine"}],
    ["61214", {nom:"L’Aigle", a:"à l’Aigle"}],
    ["62667", {nom:"Le Portel", a:"au Portel"}],
    ["71153", {nom:"Le Creusot", a:"au Creusot"}],
    ["72132", {nom:"La Ferté-Bernard", a:"à la Ferté-Bernard"}],
    ["72154", {nom:"La Flèche", a:"à la Flèche"}],
    ["72181", {nom:"Le Mans", a:"au Mans"}],
    ["73179", {nom:"La Motte-Servolex", a:"à la Motte-Servolex"}],
    ["73213", {nom:"La Ravoire", a:"à la Ravoire"}],
    ["74224", {nom:"La Roche-sur-Foron", a:"à la Roche-sur-Foron"}],
    ["76322", {nom:"Le Grand-Quevilly", a:"au Grand-Quevilly"}],
    ["76351", {nom:"Le Havre", a:"au Havre"}],
    ["76429", {nom:"Le Mesnil-Esnard", a:"au Mesnil-Esnard"}],
    ["76498", {nom:"Le Petit-Quevilly", a:"au Petit-Quevilly"}],
    ["77183", {nom:"La Ferté-sous-Jouarre", a:"à la Ferté-sous-Jouarre"}],
    ["77285", {nom:"Le Mée-sur-Seine", a:"au Mée-sur-Seine"}],
    ["78126", {nom:"La Celle-Saint-Cloud", a:"à la Celle-Saint-Cloud"}],
    ["78158", {nom:"Le Chesnay-Rocquencourt", a:"au Chesnay-Rocquencourt"}],
    ["78165", {nom:"Les Clayes-sous-Bois", a:"aux Clayes-sous-Bois"}],
    ["78440", {nom:"Les Mureaux", a:"aux Mureaux"}],
    ["78481", {nom:"Le Pecq", a:"au Pecq"}],
    ["78650", {nom:"Le Vésinet", a:"au Vésinet"}],
    ["83016", {nom:"Le Beausset", a:"au Beausset"}],
    ["83047", {nom:"La Crau", a:"à la Crau"}],
    ["83054", {nom:"La Farlède", a:"à la Farlède"}],
    ["83062", {nom:"La Garde", a:"à la Garde"}],
    ["83071", {nom:"La Londe-les-Maures", a:"à la Londe-les-Maures"}],
    ["83073", {nom:"Le Luc", a:"au Luc"}],
    ["83086", {nom:"Le Muy", a:"au Muy"}],
    ["83098", {nom:"Le Pradet", a:"au Pradet"}],
    ["83126", {nom:"La Seyne-sur-Mer", a:"à la Seyne-sur-Mer"}],
    ["83144", {nom:"La Valette-du-Var", a:"à la Valette-du-Var"}],
    ["84054", {nom:"L’Isle-sur-la-Sorgue", a:"à l’Isle-sur-la-Sorgue"}],
    ["84092", {nom:"Le Pontet", a:"au Pontet"}],
    ["84132", {nom:"Le Thor", a:"au Thor"}],
    ["85109", {nom:"Les Herbiers", a:"aux Herbiers"}],
    ["85178", {nom:"Le Poiré-sur-Vie", a:"au Poiré-sur-Vie"}],
    ["85191", {nom:"La Roche-sur-Yon", a:"à la Roche-sur-Yon"}],
    ["85194", {nom:"Les Sables-d’Olonne", a:"aux Sables-d’Olonne"}],
    ["91692", {nom:"Les Ulis", a:"aux Ulis"}],
    ["92035", {nom:"La Garenne-Colombes", a:"à la Garenne-Colombes"}],
    ["92060", {nom:"Le Plessis-Robinson", a:"au Plessis-Robinson"}],
    ["93007", {nom:"Le Blanc-Mesnil", a:"au Blanc-Mesnil"}],
    ["93013", {nom:"Le Bourget", a:"au Bourget"}],
    ["93027", {nom:"La Courneuve", a:"à la Courneuve"}],
    ["93039", {nom:"L’Île-Saint-Denis", a:"à l’Île-Saint-Denis"}],
    ["93045", {nom:"Les Lilas", a:"aux Lilas"}],
    ["93057", {nom:"Les Pavillons-sous-Bois", a:"aux Pavillons-sous-Bois"}],
    ["93061", {nom:"Le Pré-Saint-Gervais", a:"au Pré-Saint-Gervais"}],
    ["93062", {nom:"Le Raincy", a:"au Raincy"}],
    ["94038", {nom:"L’Haÿ-les-Roses", a:"à l’Haÿ-les-Roses"}],
    ["94043", {nom:"Le Kremlin-Bicêtre", a:"au Kremlin-Bicêtre"}],
    ["94058", {nom:"Le Perreux-sur-Marne", a:"au Perreux-sur-Marne"}],
    ["94059", {nom:"Le Plessis-Trévise", a:"au Plessis-Trévise"}],
    ["94060", {nom:"La Queue-en-Brie", a:"à la Queue-en-Brie"}],
    ["95313", {nom:"L’Isle-Adam", a:"à l’Isle-Adam"}],
    ["97101", {nom:"Les Abymes", a:"aux Abymes"}],
    ["97113", {nom:"Le Gosier", a:"au Gosier"}],
    ["97117", {nom:"Le Moule", a:"au Moule"}],
    ["97210", {nom:"Le François", a:"au François"}],
    ["97213", {nom:"Le Lamentin", a:"au Lamentin"}],
    ["97217", {nom:"Le Marin", a:"au Marin"}],
    ["97222", {nom:"Le Robert", a:"au Robert"}],
    ["97230", {nom:"La Trinité", a:"à la Trinité"}],
    ["97232", {nom:"Le Vauclin", a:"au Vauclin"}],
    ["97401", {nom:"Les Avirons", a:"aux Avirons"}],
    ["97404", {nom:"L’Étang-Salé", a:"à l’Étang-Salé"}],
    ["97407", {nom:"Le Port", a:"au Port"}],
    ["97408", {nom:"La Possession", a:"à la Possession"}],
    ["97422", {nom:"Le Tampon", a:"au Tampon"}]
];

const prepositions = new Map(liste);
export default prepositions;
