const types = ["rue","place","cours","quai","boulevard","avenue","allée","voie","passage", "route", "impasse", "chemin"];
const odonymiques = [		
    {nom:"Ampère", booleen: true},
    {nom:"Ausone", booleen: true},
    {nom:"Beaurepaire", booleen: true},
    {nom:"Bir-Hakeim", booleen: true},
    {nom:"Branly", booleen: true},
    {nom:"Brutus", booleen: true},
    {nom:"Casablanca", booleen: true},
    {nom:"Citoyenne", booleen: true},
    {nom:"Civique", booleen: true},
    {nom:"Claude Debussy", booleen: true},
    {nom:"Esprit-des-Lois", booleen: true},
    {nom:"Fructidor", booleen: true},
    {nom:"Gabriel Fauré", booleen: true},
    {nom:"Grand’Rue", booleen: false},
    {nom:"Grande Rue", booleen: false},
    {nom:"Haine-aux-Tyrans", booleen: true},
    {nom:"Hector Berlioz", booleen: true},
    {nom:"Henri Dunant ", booleen: true},
    {nom:"Jean Jaurès", booleen: true},
    {nom:"Jean Moulin", booleen: true},
    {nom:"John Coltrane", booleen: true},    
    {nom:"Judaïque", booleen: true},
    {nom:"Longchamps", booleen: true},
    {nom:"Marin Marais", booleen: true},
    {nom:"Maupassant", booleen: true},
    {nom:"Messidor", booleen: true},
    {nom:"Montaigne", booleen: true},
    {nom:"Nationale", booleen: true},
    {nom:"Nationale", booleen: true},
    {nom:"Neuve Saint-Seurin", booleen: true},
    {nom:"Pasteur", booleen: true},
    {nom:"Pey-Berland", booleen: true},
    {nom:"Picard", booleen: true},
    {nom:"Plus-de-Rois", booleen: true},
    {nom:"Primidi", booleen: true},
    {nom:"Principale", booleen: true},
    {nom:"Richelieu", booleen: true},
    {nom:"Saint Christoly", booleen: true},
    {nom:"Saint Projet", booleen: true},
    {nom:"Saint-Bruno", booleen: true},
    {nom:"Saint-Martial", booleen: true},
    {nom:"Saint-Paul-Saint-Seurin", booleen: true},
    {nom:"Saint-Pierre", booleen: true},
    {nom:"Saint-Étienne", booleen: true},
    {nom:"Sainte Eulalie", booleen: true},
    {nom:"Sainte-Catherine", booleen: true},
    {nom:"Sainte-Croix", booleen: true},
    {nom:"Sainte-Sophie", booleen: true},
    {nom:"Sainte-Thérèse", booleen: true},
    {nom:"Satie", booleen: true},
    {nom:"Stalingrad", booleen: true},
    {nom:"Taciturne", booleen: true},
    {nom:"Thermidor", booleen: true},
    {nom:"Victor-Hugo", booleen: true},
    {nom:"Vivre-Libre-Ou-Mourir", booleen: true},
    {nom:"de Bacalan", booleen: true},
    {nom:"de Castelmoron", booleen: true},
    {nom:"de Créon", booleen: true},
    {nom:"de Gemmapes", booleen: true},
    {nom:"de Lerme", booleen: true},
    {nom:"de Leyre", booleen: true},
    {nom:"de Montbazon", booleen: true},
    {nom:"de Moscou", booleen: true},
    {nom:"de Paludate", booleen: true},
    {nom:"de la Bourse", booleen: true},
    {nom:"de la Chartreuse", booleen: true},
    {nom:"de la Comédie", booleen: true},
    {nom:"de la Conciliation", booleen: true},
    {nom:"de la Concorde", booleen: true},
    {nom:"de la Convention", booleen: true},
    {nom:"de la Croix-Blanche", booleen: true},
    {nom:"de la Dauphine", booleen: true},
    {nom:"de la Douane", booleen: true},
    {nom:"de la Délivrance", booleen: true},
    {nom:"de la Ferme de Richemont", booleen: true},
    {nom:"de la Fidélité", booleen: true},
    {nom:"de la Fontaine", booleen: true},
    {nom:"de la Fraternité", booleen: true},
    {nom:"de la Frugalité", booleen: true},
    {nom:"de la Gare", booleen: true},
    {nom:"de la Grave", booleen: true},
    {nom:"de la Joyeuse Entrée", booleen: true},
    {nom:"de la Justice", booleen: true},
    {nom:"de la Liberté", booleen: true},
    {nom:"de la Libération", booleen: true},
    {nom:"de la Lumière", booleen: true},
    {nom:"de la Mairie", booleen: true},
    {nom:"de la Monnaie", booleen: true},
    {nom:"de la Montagne", booleen: true},
    {nom:"de la Raison", booleen: true},
    {nom:"de la Régénération", booleen: true},
    {nom:"de la République", booleen: true},
    {nom:"de la Section du 10 août", booleen: true},
    {nom:"de la Surveillance", booleen: true},
    {nom:"de la Victoire", booleen: true},
    {nom:"de la botte molle", booleen: true},
    {nom:"de la plaine", booleen: true},
    {nom:"de l’Amitié", booleen: true},
    {nom:"de l’Arbre-Chéri", booleen: true},
    {nom:"de l’Empire-des-Lois", booleen: true},
    {nom:"de l’Europe", booleen: true},
    {nom:"de l’Indivisibilité", booleen: true},
    {nom:"de l’Opinion", booleen: true},
    {nom:"de l’Orme", booleen: true},
    {nom:"de l’Unité", booleen: true},
    {nom:"de l’Égalité", booleen: true},
    {nom:"de l’Église Saint-Augustin", booleen: true},
    {nom:"de l’Église", booleen: true},
    {nom:"des Amarantes", booleen: true},
    {nom:"des Amarillis", booleen: true},
    {nom:"des Basques", booleen: true},
    {nom:"des Capucins", booleen: true},
    {nom:"des Catherinettes", booleen: true},
    {nom:"des Chartrons", booleen: true},
    {nom:"des Chouans", booleen: true},
    {nom:"des Cordeliers", booleen: true},
    {nom:"des Cèdres", booleen: true},
    {nom:"des Droits-de-l’Homme", booleen: true},
    {nom:"des Faures", booleen: true},
    {nom:"des Grands-Hommes", booleen: true},
    {nom:"des Hommes Libres", booleen: true},
    {nom:"des Jardins", booleen: true},
    {nom:"des Lauriers", booleen: true},
    {nom:"des Martyrs de la Résistance", booleen: true},
    {nom:"des Nations Libres", booleen: true},
    {nom:"des Palanques", booleen: true},
    {nom:"des Picques", booleen: true},
    {nom:"des Pêches", booleen: true},
    {nom:"des Queyries", booleen: true},
    {nom:"des Quinconces", booleen: true},
    {nom:"des Salinières", booleen: true},
    {nom:"des Sans-Culottes", booleen: true},
    {nom:"des Tonneliers", booleen: true},
    {nom:"des navets", booleen: true},
    {nom:"des Écoles", booleen: true},
    {nom:"du 10 août", booleen: true},
    {nom:"du 11 novembre", booleen: true},
    {nom:"du 14-juillet", booleen: true},
    {nom:"du 17 septembre", booleen: true},
    {nom:"du Basilic", booleen: true},
    {nom:"du Bec d’Ambès", booleen: true},
    {nom:"du Boeuf", booleen: true},
    {nom:"du Bonheur", booleen: true},
    {nom:"du Chamois", booleen: true},
    {nom:"du Champ de Mars", booleen: true},
    {nom:"du Chapelet", booleen: true},
    {nom:"du Château", booleen: true},
    {nom:"du Coq", booleen: true},
    {nom:"du Couvent", booleen: true},
    {nom:"du Département", booleen: true},
    {nom:"du Français libre", booleen: true},
    {nom:"du Jardin-Public", booleen: true},
    {nom:"du Jeune-Barra", booleen: true},
    {nom:"du Marché des Chartrons", booleen: true},
    {nom:"du Marché-Royal", booleen: true},
    {nom:"du Maroc", booleen: true},
    {nom:"du Moulin", booleen: true},
    {nom:"du Palais", booleen: true},
    {nom:"du Parlement", booleen: true},
    {nom:"du Peuple-Souverain", booleen: true},
    {nom:"du Pont-Long", booleen: true},
    {nom:"du Romarin", booleen: true},
    {nom:"du Réveil", booleen: true},
    {nom:"du Silence", booleen: true},
    {nom:"du Sommeil", booleen: true},
    {nom:"du Stade", booleen: true},
    {nom:"du Sénégal", booleen: true},
    {nom:"du Temple-Décadaire", booleen: true},
    {nom:"du chant des vagues", booleen: true},
    {nom:"d’Arlac", booleen: true},
    {nom:"d’Armagnac", booleen: true},
    {nom:"d’Arès", booleen: true},
    {nom:"l’Immortelle", booleen: true},
    {nom:"Ça-tiendra", booleen: true},
    {nom:"Ça-va", booleen: true},
    {nom:"Émile Zola", booleen: true}
];

export {types, odonymiques};
